// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_basic.Data;

namespace mvc_basic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220523124004_seed added")]
    partial class seedadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mvc_basic.Data.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("people");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "London",
                            Name = "Charls",
                            Number = 123
                        },
                        new
                        {
                            Id = 2,
                            City = "Sweden",
                            Name = "Carl",
                            Number = 123
                        },
                        new
                        {
                            Id = 3,
                            City = "USA",
                            Name = "Luzy",
                            Number = 123
                        },
                        new
                        {
                            Id = 4,
                            City = "Italy",
                            Name = "Mario",
                            Number = 123
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
