// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_basic.Data;

namespace mvc_basic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mvc_basic.Models.Cities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CountryId = 1,
                            Name = "London"
                        },
                        new
                        {
                            CityId = 2,
                            CountryId = 1,
                            Name = "Birmingham"
                        },
                        new
                        {
                            CityId = 3,
                            CountryId = 1,
                            Name = "Glasgow"
                        },
                        new
                        {
                            CityId = 4,
                            CountryId = 1,
                            Name = "Liverpool"
                        },
                        new
                        {
                            CityId = 5,
                            CountryId = 2,
                            Name = "Moscow"
                        },
                        new
                        {
                            CityId = 6,
                            CountryId = 2,
                            Name = "Saint Petersburg"
                        },
                        new
                        {
                            CityId = 7,
                            CountryId = 2,
                            Name = "Novosibirsk"
                        },
                        new
                        {
                            CityId = 8,
                            CountryId = 2,
                            Name = "Yekaterinburg"
                        },
                        new
                        {
                            CityId = 9,
                            CountryId = 3,
                            Name = "Madrid"
                        },
                        new
                        {
                            CityId = 10,
                            CountryId = 3,
                            Name = "Barcelona"
                        },
                        new
                        {
                            CityId = 11,
                            CountryId = 3,
                            Name = "Valencia"
                        },
                        new
                        {
                            CityId = 12,
                            CountryId = 3,
                            Name = "Seville"
                        },
                        new
                        {
                            CityId = 13,
                            CountryId = 4,
                            Name = "Stockholm"
                        },
                        new
                        {
                            CityId = 14,
                            CountryId = 4,
                            Name = "Gothenburg"
                        },
                        new
                        {
                            CityId = 15,
                            CountryId = 4,
                            Name = "Malmö"
                        },
                        new
                        {
                            CityId = 16,
                            CountryId = 4,
                            Name = "Uppsala"
                        });
                });

            modelBuilder.Entity("mvc_basic.Models.Countrys.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("countrys");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "England"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Russia"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Spain"
                        });
                });

            modelBuilder.Entity("mvc_basic.Models.Languages.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageID = 1,
                            Name = "Spanish"
                        },
                        new
                        {
                            LanguageID = 2,
                            Name = "France"
                        });
                });

            modelBuilder.Entity("mvc_basic.Models.ManyToMany.LanguagePeople", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleId")
                        .HasColumnType("int");

                    b.HasKey("LanguageId", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("LanguagePeople");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            PeopleId = 1
                        });
                });

            modelBuilder.Entity("mvc_basic.Models.People", b =>
                {
                    b.Property<int>("PeopleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("PeopleId");

                    b.HasIndex("CityId");

                    b.ToTable("people");

                    b.HasData(
                        new
                        {
                            PeopleId = 1,
                            CityId = 1,
                            Name = "Simon",
                            Number = 123
                        },
                        new
                        {
                            PeopleId = 2,
                            CityId = 4,
                            Name = "Frans",
                            Number = 123
                        },
                        new
                        {
                            PeopleId = 3,
                            CityId = 5,
                            Name = "Roger",
                            Number = 123
                        },
                        new
                        {
                            PeopleId = 4,
                            CityId = 9,
                            Name = "Alf",
                            Number = 123
                        },
                        new
                        {
                            PeopleId = 5,
                            CityId = 12,
                            Name = "Bruno",
                            Number = 123
                        },
                        new
                        {
                            PeopleId = 6,
                            CityId = 13,
                            Name = "Shan",
                            Number = 123
                        },
                        new
                        {
                            PeopleId = 7,
                            CityId = 14,
                            Name = "Elf",
                            Number = 123
                        });
                });

            modelBuilder.Entity("mvc_basic.Models.Cities.City", b =>
                {
                    b.HasOne("mvc_basic.Models.Countrys.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("mvc_basic.Models.ManyToMany.LanguagePeople", b =>
                {
                    b.HasOne("mvc_basic.Models.Languages.Language", "Language")
                        .WithMany("LanguagePeople")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc_basic.Models.People", "People")
                        .WithMany("LanguagePeople")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("People");
                });

            modelBuilder.Entity("mvc_basic.Models.People", b =>
                {
                    b.HasOne("mvc_basic.Models.Cities.City", "City")
                        .WithMany("Peoples")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("mvc_basic.Models.Cities.City", b =>
                {
                    b.Navigation("Peoples");
                });

            modelBuilder.Entity("mvc_basic.Models.Countrys.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("mvc_basic.Models.Languages.Language", b =>
                {
                    b.Navigation("LanguagePeople");
                });

            modelBuilder.Entity("mvc_basic.Models.People", b =>
                {
                    b.Navigation("LanguagePeople");
                });
#pragma warning restore 612, 618
        }
    }
}
